device: cuda
guidance_scale: 7.5
latents_path: latents_forward
n_timesteps: 50
negative_prompt: ugly, blurry, black, low res, unrealistic
output_path: PNP-results/horse
pnp_attn_t: 0.5
pnp_f_t: 0.8
seed: 1
