# general
seed: 1
device: 'cuda'
output_path: 'PNP-results/horse'

# data
latents_path: 'latents_forward'

# diffusion
guidance_scale: 7.5
n_timesteps: 50
negative_prompt: ugly, blurry, black, low res, unrealistic

# pnp injection thresholds, ∈ [0, 1]
pnp_attn_t: 0.5
pnp_f_t: 0.8
